In [1]:
import pandas as pd

Forward Motion Dataframe From Autocoll 2303

In [5]:
df_forwardAutocoll_2303 = pd.read_csv('../ALS/AutoColl 2303/AC_AIF2303-1.txt', header=13, delimiter='\t')
df_forwardAutocoll_2303

,Time of Day,Time (s),X,AI 0,DMI,X Velocity,Y Velocity,AI 1,AI 2,Tiltmeter 1,...,Tilt 1,Tilt 2,Temperature,Attocube position,Attocube temperature,Attocube RH%,Attocube hPa,Attocube Ref Index,Pressure from Xrol-monitor,Flow Meter from Xrol-monitor
0,10:48:44,3.713,-154.49998,-8.073022,0.0,0.0,0.0,-8.089955,-8.077069,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,10:48:48,7.276,-154.45000,-7.855280,0.0,0.0,0.0,-7.871460,-7.859082,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,10:48:51,10.951,-154.40000,-7.647312,0.0,0.0,0.0,-7.662775,-7.651014,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,10:48:55,14.497,-154.35002,-7.442530,0.0,0.0,0.0,-7.457292,-7.445992,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,10:48:59,18.059,-154.30000,-7.244767,0.0,0.0,0.0,-7.258740,-7.248051,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,10:49:02,21.653,-154.25000,-7.057649,0.0,0.0,0.0,-7.070950,-7.060739,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,10:49:06,25.057,-154.20000,-6.872158,0.0,0.0,0.0,-6.884798,-6.875047,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,10:49:09,28.668,-154.15002,-6.696195,0.0,0.0,0.0,-6.708191,-6.698928,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,10:49:13,32.279,-154.10002,-6.531826,0.0,0.0,0.0,-6.543252,-6.534379,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,10:49:16,35.889,-154.04998,-6.368172,0.0,0.0,0.0,-6.379053,-6.370569,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,10:49:20,39.387,-153.99998,-6.212748,0.0,0.0,0.0,-6.223085,-6.214969,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,10:49:24,43.111,-153.95002,-6.066437,0.0,0.0,0.0,-6.076318,-6.068540,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,10:49:27,46.785,-153.90002,-5.920698,0.0,0.0,0.0,-5.930113,-5.922649,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,10:49:31,50.396,-153.84998,-5.785217,0.0,0.0,0.0,-5.794232,-5.787018,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,10:49:34,53.944,-153.80002,-5.651735,0.0,0.0,0.0,-5.660312,-5.653394,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,10:49:38,57.441,-153.75002,-5.519984,0.0,0.0,0.0,-5.528166,-5.521518,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,10:49:41,60.845,-153.69998,-5.394862,0.0,0.0,0.0,-5.402665,-5.396294,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,10:49:45,64.438,-153.65000,-5.275830,0.0,0.0,0.0,-5.283316,-5.277113,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,10:49:49,68.066,-153.60002,-5.166148,0.0,0.0,0.0,-5.173314,-5.167356,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,10:49:52,71.468,-153.55002,-5.055770,0.0,0.0,0.0,-5.062593,-5.056870,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,10:49:56,75.175,-153.49998,-4.950950,0.0,0.0,0.0,-4.957494,-4.951947,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Select Columns 'X', "Raw Autocoll X'

In [6]:
x_rawAutocollX_forward = df_forwardAutocoll_2303[['X', 'Raw Autocoll X']]
x_rawAutocollX_forward

            X  Raw Autocoll X
0  -154.49998             NaN
1  -154.45000             NaN
2  -154.40000             NaN
3  -154.35002             NaN
4  -154.30000             NaN
5  -154.25000        0.000063
6  -154.20000        0.000068
7  -154.15002        0.000073
8  -154.10002        0.000079
9  -154.04998        0.000084
10 -153.99998        0.000086
11 -153.95002        0.000087
12 -153.90002        0.000089
13 -153.84998        0.000091
14 -153.80002        0.000093
15 -153.75002        0.000096
16 -153.69998        0.000099
17 -153.65000        0.000101
18 -153.60002        0.000103
19 -153.55002        0.000104
20 -153.49998        0.000106

Set Column 'X' to Index

In [7]:
x_rawAutocollX_forward.set_index('X', inplace=True)
x_rawAutocollX_forward

            Raw Autocoll X
X
-154.49998             NaN
-154.45000             NaN
-154.40000             NaN
-154.35002             NaN
-154.30000             NaN
-154.25000        0.000063
-154.20000        0.000068
-154.15002        0.000073
-154.10002        0.000079
-154.04998        0.000084
-153.99998        0.000086
-153.95002        0.000087
-153.90002        0.000089
-153.84998        0.000091
-153.80002        0.000093
-153.75002        0.000096
-153.69998        0.000099
-153.65000        0.000101
-153.60002        0.000103
-153.55002        0.000104
-153.49998        0.000106

Reverse Motion From Autocoll 2303

In [8]:
df_reverseAutocoll_2303 = pd.read_csv('../ALS/AutoColl 2301/AC_AIR2301-2.txt', header=13, delimiter='\t')
df_reverseAutocoll_2303

,Time of Day,Time (s),X,AI 0,DMI,X Velocity,Y Velocity,AI 1,AI 2,Tiltmeter 1,...,Tilt 1,Tilt 2,Temperature,Attocube position,Attocube temperature,Attocube RH%,Attocube hPa,Attocube Ref Index,Pressure from Xrol-monitor,Flow Meter from Xrol-monitor
0,10:28:40,151.307,-155.00000,-4.315850,0.0,0.0,0.0,-4.320772,-4.316378,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,10:28:37,147.854,-154.90000,-4.399379,0.0,0.0,0.0,-4.404543,-4.400003,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,10:28:33,144.291,-154.79992,-4.484411,0.0,0.0,0.0,-4.489789,-4.485092,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,10:28:30,140.633,-154.69998,-4.569756,0.0,0.0,0.0,-4.575333,-4.570533,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,10:28:26,137.006,-154.60000,-4.659756,0.0,0.0,0.0,-4.665564,-4.660617,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,10:28:22,133.333,-154.49998,-4.755813,0.0,0.0,0.0,-4.761889,-4.756696,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,10:28:19,129.738,-154.40004,-4.854118,0.0,0.0,0.0,-4.860441,-4.855034,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,10:28:15,126.176,-154.29998,-4.952136,0.0,0.0,0.0,-4.958690,-4.953172,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,10:28:12,122.564,-154.20002,-5.054977,0.0,0.0,0.0,-5.061780,-5.056026,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,10:28:08,118.907,-154.10002,-5.161034,0.0,0.0,0.0,-5.168181,-5.162271,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,10:28:04,115.167,-154.00000,-5.275388,0.0,0.0,0.0,-5.282885,-5.276706,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,10:28:01,111.558,-153.90002,-5.383849,0.0,0.0,0.0,-5.391626,-5.385221,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,10:27:57,107.931,-153.79998,-5.501624,0.0,0.0,0.0,-5.509746,-5.503151,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,10:27:53,104.337,-153.69998,-5.630906,0.0,0.0,0.0,-5.639401,-5.632518,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,10:27:50,100.886,-153.60000,-5.755040,0.0,0.0,0.0,-5.763915,-5.756778,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,10:27:46,97.290,-153.49998,-5.883426,0.0,0.0,0.0,-5.892640,-5.885247,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,10:27:43,93.727,-153.40002,-6.019865,0.0,0.0,0.0,-6.029565,-6.021883,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,10:27:39,90.054,-153.29998,-6.166090,0.0,0.0,0.0,-6.176222,-6.168266,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,10:27:36,86.505,-153.20000,-6.320777,0.0,0.0,0.0,-6.331408,-6.323069,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,10:27:32,82.943,-153.09998,-6.478850,0.0,0.0,0.0,-6.490059,-6.481355,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,10:27:28,79.316,-153.00002,-6.645778,0.0,0.0,0.0,-6.657507,-6.648411,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Select Columns 'X', 'Raw Autocoll X' From Dataframe

In [10]:
x_rawAutocollX_reverse = df_reverseAutocoll_2303[['X', 'Raw Autocoll X']]
x_rawAutocollX_reverse

            X  Raw Autocoll X
0  -155.00000             NaN
1  -154.90000             NaN
2  -154.79992             NaN
3  -154.69998             NaN
4  -154.60000             NaN
5  -154.49998             NaN
6  -154.40004             NaN
7  -154.29998             NaN
8  -154.20002        0.000068
9  -154.10002        0.000079
10 -154.00000        0.000086
11 -153.90002        0.000089
12 -153.79998        0.000094
13 -153.69998        0.000099
14 -153.60000        0.000103
15 -153.49998        0.000106
16 -153.40002        0.000108
17 -153.29998        0.000108
18 -153.20000        0.000106
19 -153.09998        0.000103
20 -153.00002        0.000100

Set Column 'X' as Index

In [11]:
x_rawAutocollX_reverse.set_index('X', inplace=True)
x_rawAutocollX_reverse

            Raw Autocoll X
X
-155.00000             NaN
-154.90000             NaN
-154.79992             NaN
-154.69998             NaN
-154.60000             NaN
-154.49998             NaN
-154.40004             NaN
-154.29998             NaN
-154.20002        0.000068
-154.10002        0.000079
-154.00000        0.000086
-153.90002        0.000089
-153.79998        0.000094
-153.69998        0.000099
-153.60000        0.000103
-153.49998        0.000106
-153.40002        0.000108
-153.29998        0.000108
-153.20000        0.000106
-153.09998        0.000103
-153.00002        0.000100